### ISSUE TITLE
Escaping characters

### ISSUE THREAD

**Issue by yyon** [mxxii/parseley#97]
Hello, I'm trying to match an id that contains a dot character, but it throws an error:
```
[Error] Unhandled Promise Rejection: Error: invalid syntax at line 1 col 10:

1  #sceneI_3\.1
            ^
Unexpected input (lexer error). Instead, I was expecting to see one of the following:

A hashToken token based on:
    idSelector...
	handleError (chunk-QFNPXTZX.js:1062)
	runUpdates (chunk-QFNPXTZX.js:876)
	completeLoad (chunk-QFNPXTZX.js:310)
	loadEnd (chunk-QFNPXTZX.js:305)
```
It doesn't work with or without the backslash. Looking at [https://github.com/mxxii/parseley/blob/main/src/parser.ts](https://github.com/mxxii/parseley/blob/main/src/parser.ts), it looks like IDs are matched against the regex `/#[a-zA-Z0-9_-]+/`, making it impossible to match an ID with a dot in it.
I was using the [html-to-text library](https://www.npmjs.com/package/html-to-text), which uses this library to match CSS.

**Comment by KillyMXI** [comment]
Thanks for the report.
ID with a dot seems like something evil.

Quick googling leads to SO question: https://stackoverflow.com/questions/12310090/css-selector-with-period-in-id

- I have to review the spec to implement the escape character: https://www.w3.org/TR/CSS2/syndata.html#value-def-identifier

- As a workaround, `[id='sceneI_3.1']` should hopefully work, albeit with a lower specificity.

(Note: for `html-to-text` it is better to write `tag#id` or `tag[id=id]` than `#id` or `[id=id]`.)

**Comment by yyon** [comment]
The `[id='sceneI_3.1']` workaround works, thanks! An ID with a dot does seem pretty evil, agreed.
